name: Publish to github

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ${{ vars.RUNNER  || 'ubuntu-latest' }}

    permissions:
      contents: read
      packages: write


    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}